### ISSUE TITLE
官方 webview 无效果

### ISSUE THREAD

**Issue by supermebing** [Jayshanx/flutter_jsbridge#1]

**Comment by Jayshanx** [comment]
我本地跑了项目是可以的， 具体可以在 js 里面 console看看执行到哪一步

**Comment by supermebing** [comment]
JSSDK.getUserInfo 这个方法执行后没反应     jssdk.js 需要重新编译吗   现在是inapp_webview 效果可以 但是官方的不行   可以微信沟通下吗   c289373433

**Comment by supermebing** [comment]
已解决
